### ISSUE TITLE
Rhino 7.0 GH LBT install problematic 

### ISSUE THREAD

**Issue by NicholasFry** [ladybug-tools/lbt-grasshopper#1294]
Hi there. I am a completely new user to Rhino, LBT, etc. I found that the screenshots for Rhino 7.0 are irrelevant for LBT. The latest version of the GH interface does not even have words on the face of the workspace components at the installer. I could not tell if the toggle was running, not turned on, or broken. Random clicking and waiting led to prompts that Python download was complete. The same with step 2 on the installer. 
![image](https://user-images.githubusercontent.com/60554125/147776947-23fe4e6e-69db-4e82-99bd-926b94904bea.png)

**Comment by mostaphaRoudsari** [comment]
Hi @NicholasFry! Welcome to the Ladybug Tools community. You should post this question to the forum: https://discourse.ladybug.tools
