### ISSUE TITLE
All users installation

### ISSUE THREAD

**Issue by LenzWinkler** [ladybug-tools/lbt-grasshopper#1297]
The [Windows Installation Steps](https://github.com/ladybug-tools/lbt-grasshopper/wiki/1.1-Windows-Installation-Steps#windows-installation-steps) show instructions to install LBT for a single user (`C:\Users\[USERNAME]\ladybug_tools`).

How can i install LBT on a multi user system? E.g. to `C:\Users\Public\ladybug_tools` or `C:\ProgramData\ladybug_tools`

**Comment by mostaphaRoudsari** [comment]
If you use the link that I shared here (https://github.com/ladybug-tools/lbt-grasshopper/issues/1298) it will also resolve this issue.

**Comment by chriswmackey** [comment]
This has all been addressed with the Pollination Single-Click installer available here:

https://app.pollination.cloud/cad-plugins
