### ISSUE TITLE
HB Model to OSM gh component does not work in example(lbtools 1.1.0, openstudio 3.1.0)

### ISSUE THREAD

**Issue by ChildAdrian** [ladybug-tools/lbt-grasshopper#634]
it left the following error message:

0. C:\OS\src\model\PlanarSurface.cpp@663 : Cannot create a surface with vertices [[-6.50628e-05, -0.00919395, 0.003], [0.00143272, -0.00659459, 0.003], [-0.00382457, -0.00356527, 0.003], [-0.00532236, -0.00616463, 0.003]]
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/geometry/face.rb:71:in `initialize'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/geometry/face.rb:71:in `new'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/geometry/face.rb:71:in `to_openstudio'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/geometry/room.rb:156:in `block in to_openstudio'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/geometry/room.rb:154:in `each'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/geometry/room.rb:154:in `to_openstudio'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/model.rb:452:in `block in create_rooms'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/model.rb:450:in `each'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/model.rb:450:in `create_rooms'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/model.rb:231:in `create_openstudio_objects'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/from_honeybee/model.rb:147:in `to_openstudio_model'
	C:/Users/Adria/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/measures/from_honeybee_model/measure.rb:84:in `run'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/util/measure.rb:515:in `apply_measure'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/util/measure.rb:114:in `block in apply_measures'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/run.rb:292:in `step'
	:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/run.rb:234:in `run'
	:/openstudio_cli.rb:971:in `execute'
	:/openstudio_cli.rb:761:in `execute'
	:/openstudio_cli.rb:1755:in `<main>'
	eval:175:in `eval'
	eval:175:in `require_embedded_absolute'
	eval:160:in `block in require_embedded'
	eval:154:in `each'
	eval:154:in `require_embedded'
	eval:113:in `require'
	eval:3:in `<main>'
1. Runtime error (PythonException): Your Rhino Model units system is: Meters
C:\OS\src\model\PlanarSurface.cpp@663 : Cannot create a surface with vertices [[-6.50628e-05, -0.00919395, 0.003], [0.00143272, -0.00659459, 0.003], [-0.00382457, -0.00356527, 0.003], [-0.00532236, -0.00616463, 0.003]]

Traceback:
  line 234, in script

**Comment by mostaphaRoudsari** [comment]
Hi @ChildAdrian, you should post this question to the forum.

https://discourse.ladybug.tools
